# Generated by Django 3.1.2 on 2020-11-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEdit', '0002_auto_20201101_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('real/fake', 'real/fake'), ('conditional real/fake', 'conditional real/fake')], max_length=200),
        ),
    ]
