# Generated by Django 3.1.2 on 2020-11-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FEdit', '0003_auto_20201101_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
    ]
