# Generated by Django 3.1.2 on 2020-11-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEdit', '0006_auto_20201101_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='C', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
