# Generated by Django 3.1.2 on 2020-11-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEdit', '0007_auto_20201101_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='query_image_A',
        ),
        migrations.RemoveField(
            model_name='question',
            name='query_image_B',
        ),
        migrations.AddField(
            model_name='choice',
            name='query_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
