# Generated by Django 3.0.6 on 2020-11-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEdit', '0008_auto_20201101_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='query_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_ref_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single real/fake', 'single real/fake'), ('real/fake', 'real/fake'), ('conditional real/fake', 'conditional real/fake')], max_length=200),
        ),
    ]
